#!/usr/bin/env bash
# clone the host folder
cp /etc/hosts /etc/hosts.bak

sed -i '/\slocalhost$/d' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
