#!/usr/bin/env bash
# clone the host folder
sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/\slocalhost$/d' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

sudo echo "127.0.0.2   localhost localhost.localdomain localhost4 localhost4.localdomain4
::2         localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts
